# Generated by Django 2.2.4 on 2020-01-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
    ]
